/*
 * NFT Storage API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PinStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "pinning")]
    Pinning,
    #[serde(rename = "pinned")]
    Pinned,
    #[serde(rename = "failed")]
    Failed,

}

impl ToString for PinStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Queued => String::from("queued"),
            Self::Pinning => String::from("pinning"),
            Self::Pinned => String::from("pinned"),
            Self::Failed => String::from("failed"),
        }
    }
}




