// Generated by Wrangler on Tue Dec 06 2022 15:29:19 GMT-0500 (Eastern Standard Time)
interface Env {
	ENS_RESOLVER_URL: "https://api.ensideas.com/ens/resolve/";
	Core: DurableObjectNamespace;
	CryptoCore: DurableObjectNamespace;
	Access: Fetcher;
	Oort: Fetcher; 
}
