PRAGMA foreign_keys=OFF;
CREATE TABLE IF NOT EXISTS "urnq_component" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar(64) NOT NULL, "value" varchar(512) NOT NULL);
CREATE TABLE IF NOT EXISTS "urnr_component" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "key" varchar(64) NOT NULL, "value" varchar(512) NOT NULL);
CREATE TABLE IF NOT EXISTS "node" ("urn" varchar(8192) PRIMARY KEY NOT NULL, "nid" varchar NOT NULL, "nss" varchar NOT NULL, "fragment" varchar NOT NULL);
CREATE TABLE IF NOT EXISTS "permission" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar NOT NULL);
CREATE TABLE IF NOT EXISTS "edge" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "tag" varchar(512) NOT NULL, "srcUrn" varchar(8192), "dstUrn" varchar(8192), CONSTRAINT "FK_7934aaa128dae90ec204dbb1bfd" FOREIGN KEY ("srcUrn") REFERENCES "node" ("urn") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_118fde23e798563fe2ee7953bcf" FOREIGN KEY ("dstUrn") REFERENCES "node" ("urn") ON DELETE NO ACTION ON UPDATE NO ACTION);
CREATE TABLE IF NOT EXISTS "node_qcomp_urnq_component" ("nodeUrn" varchar(8192) NOT NULL, "urnqComponentId" integer NOT NULL, CONSTRAINT "FK_45d7217ee65960dcb8bf0c25215" FOREIGN KEY ("nodeUrn") REFERENCES "node" ("urn") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_73c3634039a7d02cb0614ef1841" FOREIGN KEY ("urnqComponentId") REFERENCES "urnq_component" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("nodeUrn", "urnqComponentId"));
CREATE TABLE IF NOT EXISTS "node_rcomp_urnr_component" ("nodeUrn" varchar(8192) NOT NULL, "urnrComponentId" integer NOT NULL, CONSTRAINT "FK_b66713a755c2fd40b787fe3e8ad" FOREIGN KEY ("nodeUrn") REFERENCES "node" ("urn") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_927a22c66a8de3412d9bfe7451e" FOREIGN KEY ("urnrComponentId") REFERENCES "urnr_component" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("nodeUrn", "urnrComponentId"));
CREATE TABLE IF NOT EXISTS "edge_permissions_permission" ("edgeId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "FK_ce2e8da3e45963cf393a7918282" FOREIGN KEY ("edgeId") REFERENCES "edge" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_408364323672a4fe150ecf1ad3e" FOREIGN KEY ("permissionId") REFERENCES "permission" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("edgeId", "permissionId"));
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('edge',0);
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_a4f0c73580e9e6f12e7f7b84d3" ON "urnq_component" ("key", "value") ;
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_622f2e1467a15629238a71bce9" ON "urnr_component" ("key", "value") ;
CREATE UNIQUE INDEX IF NOT EXISTS "IDX_984490e919edd4c94e399aae97" ON "edge" ("srcUrn", "dstUrn", "tag") ;
CREATE INDEX IF NOT EXISTS "IDX_45d7217ee65960dcb8bf0c2521" ON "node_qcomp_urnq_component" ("nodeUrn") ;
CREATE INDEX IF NOT EXISTS "IDX_73c3634039a7d02cb0614ef184" ON "node_qcomp_urnq_component" ("urnqComponentId") ;
CREATE INDEX IF NOT EXISTS "IDX_b66713a755c2fd40b787fe3e8a" ON "node_rcomp_urnr_component" ("nodeUrn") ;
CREATE INDEX IF NOT EXISTS "IDX_927a22c66a8de3412d9bfe7451" ON "node_rcomp_urnr_component" ("urnrComponentId") ;
CREATE INDEX IF NOT EXISTS "IDX_ce2e8da3e45963cf393a791828" ON "edge_permissions_permission" ("edgeId") ;
CREATE INDEX IF NOT EXISTS "IDX_408364323672a4fe150ecf1ad3" ON "edge_permissions_permission" ("permissionId") ;
